services:
  mysql:
    image: mysql:8.0
    container_name: lab5
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab5
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin-lab5
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: lab5
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:

